# Generated by Django 4.2.7 on 2023-11-15 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gram', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='gram',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tg.gram'),
        ),
    ]
