# Generated by Django 4.2.7 on 2023-11-15 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0002_gram_product_gram'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
