# Generated by Django 4.2.7 on 2023-11-15 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0003_product_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
