# Generated by Django 4.2.7 on 2023-11-15 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0004_alter_chapter_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelToAnnounce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='gram',
            name='chapter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tg.chapter'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gram',
            name='usd',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
