# Generated by Django 4.2.7 on 2023-11-15 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0005_channeltoannounce_gram_chapter_gram_usd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='price',
        ),
    ]
