# Generated by Django 4.2.7 on 2023-11-15 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0006_remove_chapter_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='photo',
            field=models.CharField(blank=True, max_length=555, null=True),
        ),
    ]
