# Generated by Django 4.2.7 on 2023-11-16 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0007_chapter_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
