# Generated by Django 4.2.7 on 2023-11-18 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0008_alter_chapter_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='products',
        ),
        migrations.AddField(
            model_name='chapter',
            name='leninsky',
            field=models.ManyToManyField(related_name='leninsky', to='tg.product'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='oktyabrsky',
            field=models.ManyToManyField(related_name='oktyabrsky', to='tg.product'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='pervomaysky',
            field=models.ManyToManyField(related_name='pervomaysky', to='tg.product'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='sverdlovsky',
            field=models.ManyToManyField(related_name='sverdlovsky', to='tg.product'),
        ),
    ]
