# Generated by Django 4.2.7 on 2023-11-19 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0009_remove_chapter_products_chapter_leninsky_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='leninsky',
            field=models.ManyToManyField(blank=True, related_name='leninsky', to='tg.product'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='oktyabrsky',
            field=models.ManyToManyField(blank=True, related_name='oktyabrsky', to='tg.product'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='pervomaysky',
            field=models.ManyToManyField(blank=True, related_name='pervomaysky', to='tg.product'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='sverdlovsky',
            field=models.ManyToManyField(blank=True, related_name='sverdlovsky', to='tg.product'),
        ),
    ]
